website/SecureEmigration/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from user.views import HomeView, MainView
from manpower.views import ReportDetailView, ReportListView, ReportDeleteView, ReportVerifyView
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', MainView.as_view(), name="main"),
    url(r'^home/$', HomeView.as_view(), name="home"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportDetailView.as_view(), name="report_detail"), 
    url(r'^report/(?P<id>[0-9]+)/$', ReportDeleteView.as_view(), name="delete_report"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportVerifyView.as_view(), name="verify_report"),
    url(r'^report/list/$', ReportListView.as_view(), name="report_list"), 
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^manpower/', include('manpower.urls', namespace="manpower")),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
]



if settings.DEBUG:
	urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

website/manpower/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
	url(r'^list/$', ListView.as_view(), name="list_manpower"),
	url(r'^add/$', CreateView.as_view(), name="add_manpower"),
	url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(), name="show_manpower"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_manpower"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_manpower"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_manpower"),
	url(r'^(?P<slug>[\w-]+)/report/$', ReportView.as_view(), name="report_manpower"),
]

website/user/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^list/', ListView.as_view(), name="list_user"),
	url(r'^(?P<slug>[\w-]+)/$', ProfileView.as_view(), name="show_profile"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_profile"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_profile"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_profile"),
]

website/templates/layout/includes/footer.html
{% load staticfiles %}

<div class="page-footer">
    <div class="page-footer-inner">
        Copyright {% now "Y" %} &copy; Secure Emigration
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

website/templates/layout/includes/head.html
{% load staticfiles %}

<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Roboto:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
<link href="{% static "assets/global/plugins/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/global/plugins/simple-line-icons/simple-line-icons.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/global/plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/global/plugins/uniform/css/uniform.default.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/admin/pages/css/search.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/admin/pages/css/blog.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/admin/pages/css/news.css" %}" rel="stylesheet" type="text/css" 
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN THEME STYLES -->
<link href="{% static "assets/global/css/components-rounded.css" %}" id="style_components" rel="stylesheet" type="text/css" />
<link href="{% static "assets/global/css/plugins.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/admin/layout3/css/layout.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/admin/layout3/css/theme/default.css" %}" rel="stylesheet" type="text/css" />



{# <link id="style_color" href="{% static "assets/admin/layout3/css/themes/darkblue.css" %}" rel="stylesheet" type="text/css" /> #}
<link href="{% static "assets/admin/layout3/css/custom.css" %}" rel="stylesheet" type="text/css" />
<!-- END THEME STYLES -->

{% block extrahead %}
{% endblock extrahead %}

<link rel="shortcut icon" href="{% static "favicon.ico" %}" />

website/templates/layout/includes/javascripts.html
{% load staticfiles %}

<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{% static "assets/global/plugins/respond.min.js" %}"></script>
<script src="{% static "assets/global/plugins/excanvas.min.js" %}"></script>
<![endif]-->
<script src="{% static "assets/global/plugins/jquery.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/jquery-migrate.min.js" %}" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{% static "assets/global/plugins/jquery-ui/jquery-ui.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/bootstrap/js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/jquery.blockui.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/jquery.cokie.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/uniform/jquery.uniform.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" %}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="{% static "assets/global/scripts/metronic.js" %}" type="text/javascript"></script>
<script src="{% static "assets/admin/layout3/scripts/layout.js" %}" type="text/javascript"></script>
<script src="{% static "assets/admin/layout3/scripts/quick-sidebar.js" %}" type="text/javascript"></script>
<script src="{% static "assets/admin/layout3/scripts/demo.js" %}" type="text/javascript"></script>
<script>
jQuery(document).ready(function() {
    Metronic.init(); // init metronic core components
    Layout.init(); // init current layout
    Demo.init(); // init demo features
});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74143547-1', 'auto');
  ga('send', 'pageview');

</script>

website/templates/layout/includes/nav.html
{% load staticfiles %}
    <!-- BEGIN HEADER MENU -->
<div class="page-header-menu">
    <div class="container">
        <!-- BEGIN HEADER SEARCH BOX -->
        <form class="search-form" action="{% url 'manpower:list_manpower' %}" method="GET">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="query">
                <span class="input-group-btn">
                    <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                </span>
            </div>
        </form>
        <div class="hor-menu ">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li class="menu-dropdown classic-menu-dropdown">
                    <a data-hover="megamenu-dropdown" data-close-others="true" data-toggle="dropdown" href="javascript:;" class="hover-initialized" aria-expanded="true">
                    Manpower<i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu pull-left">
                        <li class=" dropdown">
                            <a href="{% url 'manpower:list_manpower' %}">
                            <i class="fa fa-building"></i>
                            Manpowers </a>
                        </li>
                        <li class=" dropdown">
                            <a href="{% url 'manpower:add_manpower' %}">
                            <i class="fa fa-plus"></i>
                            Add Manpower </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'report_list' %}">Reports</a>
                </li>
                <li>
                    <a href="{% url 'user:list_user' %}">Users</a>
                </li>
            </ul>
        </div>
    </div>
</div>
    <!-- END HEADER MENU -->