website/SecureEmigration/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from user.views import HomeView, MainView
from manpower.views import ReportDetailView, ReportListView, ReportDeleteView, ReportVerifyView
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', MainView.as_view(), name="main"),
    url(r'^home/$', HomeView.as_view(), name="home"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportDetailView.as_view(), name="report_detail"), 
    url(r'^report/(?P<id>[0-9]+)/$', ReportDeleteView.as_view(), name="delete_report"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportVerifyView.as_view(), name="verify_report"),
    url(r'^report/list/$', ReportListView.as_view(), name="report_list"), 
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^manpower/', include('manpower.urls', namespace="manpower")),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
]



if settings.DEBUG:
	urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

website/accounts/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

	url(r'^register/$', views.RegisterView.as_view(), name="register"),
	url(r'^login/$', views.LoginView.as_view(), name="login"),
	url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
]

website/user/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^list/', ListView.as_view(), name="list_user"),
	url(r'^(?P<slug>[\w-]+)/$', ProfileView.as_view(), name="show_profile"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_profile"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_profile"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_profile"),
]

website/templates/layout/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<meta charset="utf-8" />
    <head>
        <title>
              {% block title %}
              {% endblock title %}   
        </title>
        {% include "layout/includes/head.html" %}

        {% block extrahead %}
        {% endblock extrahead %}

        <link rel="shortcut icon" href="{% static "favicon.ico" %}" />
    </head>

    <!-- END HEAD -->

    {% block extrastyle %}
        <style type="text/css">
            .green-bg{background-color:#6ECB67;}
        </style>
    {% endblock extrastyle %}

    <body>
        <div class="page-header">
            <div class="page-header-top">
                <div class="container">
                    <div class="page-logo">
                        <a href="/">
                            <img src="{% static 'secureemigration_logo_black.png' %}" style="height:40px;" class="logo-default" />
                            </a>
                        <div class="menu-toggler sidebar-toggler hide">
                        </div>
                    </div>
                    <a href="javascript:;" class="menu-toggler"></a>
                    <div class="top-menu">
                        <ul class="nav navbar-nav pull-right">
                            <li class="dropdown dropdown-user dropdown-dark">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                {% if request.user.is_active%}
                                <img alt="" class="img-circle" src="{% static 'default.png' %}">
                                {% endif %}
                                <span class="username username-hide-mobile">
                                    {% if request.user.is_active %}
                                      {% if request.user.is_superuser %}
                                      Administrator
                                      {% else %}        
                                      {{request.user.get_full_name}}
                                      {% endif %}
                                    {% else %}
                                      Sign In / Up
                                    {% endif %}<i class="fa fa-angle-down"></i>
                                </span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-default">
                                    {% if request.user.is_active %}
                                    <li><a href="{% url 'user:show_profile' request.user|slugify %}"><span class="fa fa-user"></span> Profile</a></li>
                                    <li><a href="{% url 'user:update_profile' request.user|slugify %}"><span class="fa fa-pencil"></span> Update</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{% url 'accounts:logout' %}"><span class="fa fa-sign-out"></span> Logout</a></li>
                                  {% else %}
                                     <li><a href="{% url 'accounts:register' %}"><span class="fa fa-pencil"></span> Register</a></li>
                                      <li><a href="{% url 'accounts:login' %}"><span class="fa fa-sign-in"></span> Login</a></li>
                                  {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            {% include "layout/includes/nav.html" %}
        </div>
        <div class="page-container">
        <!-- BEGIN PAGE CONTENT INNER -->
            <div class="page-head">
                <div class="container">
                    <div class="page-title">
                        <h1>{{title}}</h1>
                    </div>
                </div>
            </div>
            <div class="page-content">
                <div class="container">
                {% block main %}

                {% endblock main %}
                {% block content %}

                {% endblock content %}
                </div>
            </div>
        </div>
        <div class="page-prefooter">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>About</h2>
                <p>
                    सुरक्षित बैदेशिक रोजगारी
                </p>
            </div>
            <div class="col-md-3 col-sm-6 col-xs12 footer-block">
                <h2>Subscribe Email</h2>
                <div class="subscribe-form">
                    <form action="javascript:;">
                        <div class="input-group">
                            <input type="text" placeholder="mail@email.com" class="form-control">
                            <span class="input-group-btn">
                            <button class="btn" type="submit">Submit</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>Follow Us On</h2>
                <ul class="social-icons">
                    <li>
                        <a href="javascript:;" data-original-title="rss" class="rss"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="googleplus" class="googleplus"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="youtube" class="youtube"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="vimeo" class="vimeo"></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>Contacts</h2>
                <address class="margin-bottom-40">
                Team Binary<br/>
                Phone: 984 123 3456<br>
                 Email: <a href="mailto:info@metronic.com">info@teambinary.com.com</a>
                </address>
            </div>
        </div>
    </div>
</div>
<!-- END PRE-FOOTER -->

        <div class="row">
        </div>
        <div class="page-footer">
            <div class="container">
                Copyright {% now "Y" %} &copy; Secure Emigration
            </div>
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
        {% include "layout/includes/javascripts.html" %}

        {% block extrajs %}
        {% endblock extrajs %}
    </body>

</html>