website/SecureEmigration/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from user.views import HomeView, MainView
from manpower.views import ReportDetailView, ReportListView, ReportDeleteView, ReportVerifyView
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', MainView.as_view(), name="main"),
    url(r'^home/$', HomeView.as_view(), name="home"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportDetailView.as_view(), name="report_detail"), 
    url(r'^report/(?P<id>[0-9]+)/$', ReportDeleteView.as_view(), name="delete_report"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportVerifyView.as_view(), name="verify_report"),
    url(r'^report/list/$', ReportListView.as_view(), name="report_list"), 
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^manpower/', include('manpower.urls', namespace="manpower")),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
]



if settings.DEBUG:
	urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

website/user/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^list/', ListView.as_view(), name="list_user"),
	url(r'^(?P<slug>[\w-]+)/$', ProfileView.as_view(), name="show_profile"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_profile"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_profile"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_profile"),
]

website/user/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django.db import models
from django.db.models.signals import pre_save, post_save

from django.utils.text import slugify
from django.core.urlresolvers import reverse

# Create your models here.

def upload_location(instance, filename):
	return "%s/%s/%s" %("user",instance.user.username,filename)

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	contact_no = models.CharField(max_length=15, null=True)
	address = models.CharField(max_length=100)
	image = models.ImageField(upload_to=upload_location, null=True, height_field="height_field", width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	citizenship_num = models.CharField(max_length=20,null=True)
	bio = models.TextField(null=True)
	birth_date = models.DateField(null=True)
	blocked = models.BooleanField(default=False)
	manpower = models.CharField(max_length=100,null=True)
	country = models.CharField(max_length=100, null=True)
	slug = models.SlugField(unique=True)


	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse("user:show_profile", kwargs={"slug":self.slug})


def create_slug(sender, instance, *args, **kwargs):
	slug = slugify(instance.user.username,)
	instance.slug = slug

pre_save.connect(create_slug, sender=UserProfile)

def create_user_profile(sender, instance, created, **kwargs):  
	if created:
		profile, created = UserProfile.objects.get_or_create(user=instance)  

post_save.connect(create_user_profile, sender=User) 

website/user/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User


class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = [
			"contact_no",
			"image",
			"citizenship_num",
			"bio",
			"birth_date",
			"address",
			"manpower",
			"country",
		]
		widgets={
			"contact_no":forms.TextInput(attrs={
				'required':'true',
				'placeholder':'Contact No',
				'class': 'form-control',
				}
			),
			"image":forms.ClearableFileInput(attrs={
				'required':'true',
				'placeholder':'Image',
				}
			),
			"citizenship_num":forms.TextInput(attrs={
				'required':'true',
				'placeholder':'Citizenship No',
				'class': 'form-control',
				}
			),
			"bio":forms.Textarea(attrs={
				'required':'true',
				'placeholder':'Bio',
				'class': 'form-control col-md-10',
				'rows':'8',	
				}
			),
			"birth_date":forms.DateInput(attrs={
				'required':'true',
				'placeholder':'Birthdate',
				'class': 'form-control',
				}
			),
			"address":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Address',
                'class': 'form-control',	
				}
			),
			"country":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Country',
                'class': 'form-control',	
				}
			),
			"manpower":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Manpower',
                'class': 'form-control',	
				}
			),
		}

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = [
			"first_name",
			"last_name",
			"email",
		]
		widgets = {
            "first_name": forms.TextInput(attrs={
                'required': 'true',
                'placeholder': 'First Name',
                'class': 'form-control',
            	}
                # label='F'
            ),
            "last_name": forms.TextInput(attrs={
                'required': 'true',
                'placeholder': 'Last Name',
                'class': 'form-control',
            	}
                # label='F'
            ),
            "email": forms.TextInput(attrs={
                'required': 'true',
                'placeholder': 'example@example.com',
                'class': 'form-control',
            	}
            ),
        }

website/user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger	
from manpower.models import Manpower

from .models import UserProfile
from .forms import UserForm, UserProfileForm


# Create your views here.

class HomeView(View):

	def get(self,request):
		object_list = Manpower.objects.all().order_by("-average_rating")

		paginator = Paginator(object_list, 2) # Show 25 contacts per page
		page_request_var = "page"
		page = request.GET.get(page_request_var)
		try:
			object = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			object = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			object = paginator.page(paginator.num_pages)


		context = {
			"object_list": object, 
			"page_request_var": page_request_var,
			"title":"List of Top Rated Manpowers",
		}

		return render(request, "home.html", context)

class MainView(View):

	def get(self, request):
		return render(request, 'main.html')

class ProfileView(	View):

	def get(self,request, slug=None):
		object = get_object_or_404(UserProfile, slug=slug)

		context = {
			"object":object,
			"title":"UserProfile"
		}
		
		return render (request, "user/profile.html", context)


class ListView(View):

	def get(self,request):
		object_list = UserProfile.objects.all() #.order_by("-timestamp")
		paginator = Paginator(object_list, 5) # Show 25 contacts per page
		page_request_var = "page"
		page = request.GET.get(page_request_var)
		try:
			object = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			object = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			object = paginator.page(paginator.num_pages)


		context = {
			"object_list": object, 
			"page_request_var": page_request_var,
			"title":"UserList"
		}
		return render(request, "user/list.html", context)


class UpdateView(View):

	def get(self,request,slug=None):
		instance = get_object_or_404(UserProfile, slug=slug)
		user_form = UserForm(instance=instance.user)
		profile_form = UserProfileForm(instance=instance)

		context = {
			"instance":instance,
			"user_form":user_form,
			"profile_form":profile_form,
			"title":"Update Profile"
		}

		return render(request, "user/update.html", context)

	def post(self, request, slug=None):
		instance = get_object_or_404(UserProfile, slug=slug)
		user_form = UserForm(request.POST or None, instance=instance.user)
		profile_form = UserProfileForm(request.POST or None,request.FILES or None,instance=instance)
		if user_form.is_valid() and profile_form.is_valid():

			user_form.save()
			profile_form.save()
			return HttpResponseRedirect(instance.get_absolute_url())
		else:
			print(user_form.errors,profile_form.errors)

		context = {
			"instance":instance,
			"title":"Update Profile"

		}

		return render (request, "user/update.html", context)

#LoginRequiredMixin
class DeleteView(View):

	def get(self,request,slug):
		instance = get_object_or_404(UserProfile, slug=slug)
		user = instance.user
		instance.delete()
		user.delete()
		
		return redirect('home')

class BlockView(View):

	def get(self,request,slug):
		instance = get_object_or_404(UserProfile, slug=slug)
		instance.blocked = True
		instance.save()
		
		return redirect('home')

website/templates/user/list.html
{% extends "layout/base.html" %}

{% block title %}
	User | Lists
{% endblock  %}


{% block content %}
<!-- BEGIN PAGE CONTAINER -->
<div class="page-container">
	<div class="page-content">
		<div class="container">
			<div class="portlet light">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-users font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">Users</span>
					</div>
				</div>
				<div class="portlet-body">
					<div class="table-scrollable">
						<table class="table table-striped table-hover">
						<thead>
						<tr>
							<th>
								S.N.
							</th>
							<th>
								 First Name
							</th>
							<th>
								 Last Name
							</th>
							<th>
								 Username
							</th>
							<th>
								 Status
							</th>
						</tr>
						</thead>
						<tbody>
						{% for object in object_list%}
						<tr>
							<td>
								{{forloop.counter}}
							</td>
							<td>
								{{object.user.first_name}}
							</td>
							<td>
								{{object.user.last_name}}
							</td>
							<td>
								<a href="{{object.get_absolute_url}}">{{object.user}}</a>
							</td>
							<td>
								{% if not object.blocked %}
									<span class="label label-md label-success">
									Verified
									</span>
								{% else %}
									<span class="label label-md label-danger">
									Blocked
									</span>
								{% endif %}
							</td>
						</tr>
						{% endfor %}
						</tbody>
						</table>
					</div>
				</div>
			</div>

			<div class="margin-top-20">
				<ul class="pagination pagination-square">
			        {% if object_list.has_previous %}
			        	<li>
			            	<a href="?{{ page_request_var }}={{ object_list.previous_page_number }} "><span aria-hidden="true">&laquo;</span></a>
			            </li>
			        {% else %}
			        	<li>
			            	<a href="#"><span aria-hidden="true">&laquo;</span></a>
			            </li>
			        {% endif %}
			        {% for i in object_list.paginator.page_range %}
			        	<li {% if i == object_list.number %}class="active"{% endif %}>
			        		<a href="?{{ page_request_var }}={{i}}">{{i}}</a>
			        	</li>
			        {% endfor %}
			        {% if object_list.has_next %}
			        	<li>
			            	<a href="?{{ page_request_var }}={{ object_list.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
			            </li>
			         {% else %}
			        	<li>
			            	<a href="#"><span aria-hidden="true">&raquo;</span></a>
			            </li>
			        {% endif %}
				</ul>
			</div>
			
		</div>
	</div>
</div>
{% endblock content %}

website/templates/user/profile.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
	Profile | {{object.user.username}}
{% endblock title%}

{% block content %}
<div class="page-container">
		<div class="page-container">
			<div class="page-content">
				<div class="container">
					<div class="portlet light">
						<div class="portlet-body">
							<div class="blog-page">
								<div class="row">
									<div class="col-md-3 article-block">
									<div class="blog-tag-data">
										<img src="{{object.image.url}}" class="img-responsive" alt="">
									</div>
									</div>
									<div class="col-md-9 blog-sidebar">
										<div class="portlet light">
											<div class="portlet-title">
												<div class="caption">
													<span style="font-size:40px;" class="caption-subject">{{object.user.get_full_name}}</span>
														{% if not object.blocked %}
														<span class="label label-success">Verified</span>
														{% else %}
														<span class="label label-danger">Blocked</span>
														{% endif %}
												</div>
												<div class="actions">
													<a href="{% url 'user:update_profile' object.slug %}" class="btn btn-circle btn-default">
													<i class="fa fa-edit"></i> Update </a>
													<a href="{% url 'user:delete_profile' object.slug %}" class="btn btn-circle btn-default">
													<i class="fa fa-trash"></i> Delete</a>
													<a href="{% url 'user:block_profile' object.slug %}" class="btn btn-circle btn-default">
													<i class="fa fa-ban"></i> Block</a>
												</div>
											</div>
											<div class="portlet-body">	
												<h4><small><span class="fa fa-user"></span></small> {{object.user.username}}</h4>
												<h4><small><span class="fa fa-map-marker"></span></small> {{object.address}}</h4>
												<h4><small><span class="fa fa-calendar"></span></small>  {{object.birth_date}}</h4>
												<h4><small><span class="fa fa-envelope"></span></small>  {{object.user.email}}</h4>
												<h4><small><span class="fa fa-phone"></span></small>  {{object.contact_no}}</h4>
												<h4><small><span class="fa fa-calculator"></span></small>  {{object.citizenship_num}}</h4>
												<h4><small><span class="fa fa-building"></span></small> {{object.manpower}}</h4>
												<h4><small><span class="fa fa-globe"></span></small> {{object.country}}</h4>
											</div>
										</div>
									</div>
								<!--end col-md-3-->
								</div>
								<hr/>
								<h4 class="bold">Biography</h4>
								{{object.bio|safe}}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>	
{% endblock content %}

website/templates/user/update.html
{% extends "layout/base.html" %}

{% block title %}
	Update | {{instance.user.username}}
{% endblock  %}


{% block content %}
<div class="portlet light">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-edit font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">Edit Personal Details</span>
            </div>
        </div>
        <div class="portlet-body form">
            <form role="form" method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-body">
                	<div class="form-group">
                        <label id="first_name" for="{{user_form.first_name.id_for_label}}" >First Name</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            	<i class="fa fa-user"></i>
                            </span>
                            {{user_form.first_name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="last_name" for="{{user_form.last_name.id_for_label}}" >Last Name</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            	<i class="fa fa-user"></i>
                            </span>
                            {{user_form.last_name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="email" for="{{user_form.email.id_for_label}}" >Email</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                           		<i class="fa fa-envelope"></i>
                            </span>
                            {{user_form.email}}
                        </div>
                    </div>
                    <div class="form-group">
    					<label id="contact_no" for="{{profile_form.contact_no.id_for_label}}" >Contact No</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            	<i class="fa fa-phone"></i>
                            </span>
                            {{profile_form.contact_no}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="citizenship_no" for="{{profile_form.citizenship_num.id_for_label}}" >Citizenship No</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            	<i class="fa fa-calculator"></i>
                            </span>
							{{profile_form.citizenship_num}}		
                        </div>
                    </div>
                    <div class="form-group">
                    	<label id="birth_date" for="{{profile_form.birth_date.id_for_label}}" >Birth Date</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            	<i class="fa fa-calendar"></i>
                            </span>
    						{{profile_form.birth_date}}
                        </div>
                    </div>
                     <div class="form-group">
                        <label id="address" for="{{profile_form.address.id_for_label}}" >Address</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-map-marker"></i>
                            </span>
                            {{profile_form.address}}        
                        </div>
                    </div>
                     <div class="form-group">
                        <label id="country" for="{{profile_form.country.id_for_label}}" >Country</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-globe"></i>
                            </span>
                            {{profile_form.country}}        
                        </div>
                    </div>
                     <div class="form-group">
                        <label id="manpower" for="{{profile_form.manpower.id_for_label}}" >Manpower</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-building"></i>
                            </span>
                            {{profile_form.manpower}}        
                        </div>
                    </div>
                     <div class="form-group">
                        <label id="bio" for="{{profile_form.bio.id_for_label}}" >Bio</label>
                        <div class="input-group">
                        	<span class="input-group-addon">
                           		<i class="fa fa-file"></i>
                            </span>
    						{{profile_form.bio}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="image" for="{{profile_form.image.id_for_label}}" >Image</label>
                        <div class="input-group">
                        	
    						{{profile_form.image}}
                        </div>
                    </div>
                   
                    <button class="margin-top-20 btn blue" type="submit">Update Profile</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}