website/SecureEmigration/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from user.views import HomeView, MainView
from manpower.views import ReportDetailView, ReportListView, ReportDeleteView, ReportVerifyView
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', MainView.as_view(), name="main"),
    url(r'^home/$', HomeView.as_view(), name="home"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportDetailView.as_view(), name="report_detail"), 
    url(r'^report/(?P<id>[0-9]+)/$', ReportDeleteView.as_view(), name="delete_report"),
    url(r'^report/(?P<id>[0-9]+)/$', ReportVerifyView.as_view(), name="verify_report"),
    url(r'^report/list/$', ReportListView.as_view(), name="report_list"), 
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^manpower/', include('manpower.urls', namespace="manpower")),
    url(r'^account/', include('accounts.urls', namespace="accounts")),
]



if settings.DEBUG:
	urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

website/manpower/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
	url(r'^list/$', ListView.as_view(), name="list_manpower"),
	url(r'^add/$', CreateView.as_view(), name="add_manpower"),
	url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(), name="show_manpower"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_manpower"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_manpower"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_manpower"),
	url(r'^(?P<slug>[\w-]+)/report/$', ReportView.as_view(), name="report_manpower"),
]

website/user/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^list/', ListView.as_view(), name="list_user"),
	url(r'^(?P<slug>[\w-]+)/$', ProfileView.as_view(), name="show_profile"),
	url(r'^(?P<slug>[\w-]+)/update/$', UpdateView.as_view(), name="update_profile"),
	url(r'^(?P<slug>[\w-]+)/delete/$', DeleteView.as_view(), name="delete_profile"),
	url(r'^(?P<slug>[\w-]+)/block/$', BlockView.as_view(), name="block_profile"),
]

website/manpower/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save

from django.core.urlresolvers import reverse
from django.utils.text import slugify


from user.models import UserProfile

# Create your models here.


def upload_location(instance, filename):
    return "%s/%s/%s" % ("manpower", instance.name, filename)

VERIFICATION_CHOICE = (
    (0, "Pending"),
    (1, "Verified"),
)


class Manpower(models.Model):
    name = models.CharField(max_length=100, unique=True)
    address = models.CharField(max_length=100)
    contact_no = models.CharField(max_length=15, unique=True)
    website = models.URLField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    registration_no = models.CharField(max_length=20, unique=True)
    verification_status = models.IntegerField(
        default=0, choices=VERIFICATION_CHOICE)
    country_list = models.TextField()
    image = models.ImageField(upload_to=upload_location, null=True,
                              height_field="height_field", width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    average_rating = models.IntegerField(default=0)
    blocked = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ["-name", ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("manpower:show_manpower", kwargs={"slug": self.slug})


def create_slug(sender, instance, *args, **kwargs):
    slug = slugify(instance.name)
    instance.slug = slug

pre_save.connect(create_slug, sender=Manpower)

RATING_CHOICE = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
)


class Review(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    manpower = models.ForeignKey(Manpower, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.content


class Report(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    manpower = models.ForeignKey(Manpower, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    verification_status = models.IntegerField(
        default=0, choices=VERIFICATION_CHOICE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("report_detail", kwargs={"id": self.id})

website/manpower/forms.py
from django import forms

from .models import Manpower, Review, Report

class ManpowerForm(forms.ModelForm):
	VERIFICATION_CHOICE = (
		(0,"Pending"),
		(1,"Verified"),
	)
	class Meta:
		model = Manpower
		fields = [
			"name",
			"address",
			"contact_no",
			"website",
			"email",
			"registration_no",
			"country_list",
			"image",
			# "verification_status",				
		]
		widgets={
			"name":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Name',
                'class': 'form-control',	
				}
			),
			"address":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Address',
                'class': 'form-control',	
				}
			),
			"contact_no":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Contact No',
                'class': 'form-control',	
				}
			),
			"website":forms.TextInput(attrs={
                'placeholder': 'hppts://www.example.com',
                'class': 'form-control',	
				}
			),
			"email":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'example@example.com',
                'class': 'form-control',	
				}
			),
			"registration_no":forms.TextInput(attrs={
				'required': 'true',
                'placeholder': 'Regitration No',
                'class': 'form-control',	
				}
			),
			"country_list":forms.Textarea(attrs={
				'required': 'true',
                'placeholder': 'Details',
                'class': 'form-control col-md-10 ',	
				}
			),
			"image":forms.ClearableFileInput(attrs={
				'required': 'true',	
				}
			)
		}


class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = [
			"rating",	
			"content",
		]
		widgets={
			"rating":forms.Select(attrs={
				'required':'true',
				'class':'form-control'

				}
			),
			"content":forms.Textarea(attrs={
				'required':'true',
				'placeholder':'Review',
				'class':'col-md-10 form-control',
				'rows':'8',
				}
			),
		}

class ReportForm(forms.ModelForm):
	class Meta:
		model = Report
		fields = [
			"title",
			"content",
		]
		widgets={
			"title":forms.TextInput(attrs={
				'required':'true',
				'placeholder':'Title',
				'class':'form-control',
				}
			),
			"content":forms.Textarea(attrs={
				'required': 'true',
                'placeholder': 'Report',
                'class':'col-md-10 form-control',
				'rows':'8',	
				}
			),
		}

website/manpower/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.contrib import messages
from django.db.models import Q

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from user.models import UserProfile
from .models import Manpower, Review, Report
from .forms import ManpowerForm, ReviewForm, ReportForm

# Create your views here.


class CreateView(View):

    def get(self, request):
        form = ManpowerForm(request.POST or None, request.FILES or None)

        context = {
            "form": form,
            "title": "Create Manpower"
        }

        return render(request, "manpower/create.html", context)

    def post(self, request):
        form = ManpowerForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            manpower = form.save(commit=False)

            if request.user.is_superuser or request.user.is_staff:
                manpower.verification_status = 1
            else:
                manpower.verification_status = 0

            manpower.save()

            return HttpResponseRedirect(manpower.get_absolute_url())
        else:
            print (form.errors)

        context = {
            "form": form,
            "title": "Create Manpower"
        }

        return render(request, "manpower/create.html", context)


class UpdateView(View):

    def get(self, request, slug=None):
        instance = get_object_or_404(Manpower, slug=slug)
        form = ManpowerForm(request.POST or None,
                            request.FILES or None, instance=instance)

        context = {
            "form": form,
            "title": "Update Manpower Details"
        }

        return render(request, "manpower/update.html", context)

    def post(self, request, slug=None):
        instance = get_object_or_404(Manpower, slug=slug)
        form = ManpowerForm(request.POST or None,
                            request.FILES or None, instance=instance)

        if form.is_valid():
            manpower = form.save(commit=False)
            if request.user.is_superuser or request.user.is_staff:
                manpower.verification_status = 1
            else:
                manpower.verification_status = 0

            manpower.save()

            return HttpResponseRedirect(manpower.get_absolute_url())

        context = {
            "form": form,
            "title": "Update Manpower Details"
        }

        return render(request, "manpower/update.html", context)


class DetailView(View):

    def get(self, request, slug):
        manpower = get_object_or_404(Manpower, slug=slug)
        form = ReviewForm(request.POST or None)

        reviews = Review.objects.filter(manpower=manpower)

        context = {
            "manpower": manpower,
            "reviews": reviews,
            "form": form,
            "title": "Manpower Details"
        }

        return render(request, "manpower/detail.html", context)

    def post(self, request, slug):
        manpower = get_object_or_404(Manpower, slug=slug)
        user = get_object_or_404(UserProfile, user=request.user)
        print(user)
        form = ReviewForm(request.POST or None)

        if form.is_valid():
            review = form.save(commit=False)
            review.user = user
            review.manpower = manpower
            review.save()
            return HttpResponseRedirect(manpower.get_absolute_url())

        context = {
            "manpower": manpower,
            "form": form,
            "title": "Manpower Details"
        }

        return render(request, "manpower/detail.html", context)


class ListView(View):

    def get(self, request):
        object_list = Manpower.objects.all().order_by("name")
        query = request.GET.get("query")
        if query:
            object_list = object_list.filter(
                Q(name__icontains=query) |
                Q(address__icontains=query) |
                Q(website__icontains=query) |
                Q(registration_no__icontains=query) |
                Q(email__icontains=query)
            ).distinct()

        paginator = Paginator(object_list, 2)  # Show 25 contacts per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            object = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            object = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of
            # results.
            object = paginator.page(paginator.num_pages)

        context = {
            "object_list": object,
            "page_request_var": page_request_var,
            "title": "List of Manpowers"
        }

        return render(request, "manpower/list.html", context)


class DeleteView(View):

    def get(self, request, slug):
        instance = get_object_or_404(Manpower, slug=slug)
        instance.delete()

        return redirect('home')


class BlockView(View):

    def get(self, request, slug):
        instance = get_object_or_404(Manpower, slug=slug)
        instance.blocked = True
        instance.save()

        return redirect('home')


class ReportView(View):
    def get(self, request, slug):
        manpower = get_object_or_404(Manpower, slug=slug)
        user = get_object_or_404(UserProfile, user=request.user)
        form = ReportForm(request.POST or None)

        context = {
            "manpower": manpower,
            "user": user,
            "form": form,
            "title": "Report a Manpower"
        }

        return render(request, "manpower/report.html", context)

    def post(self, request, slug):
        manpower = get_object_or_404(Manpower, slug=slug)
        user = get_object_or_404(UserProfile, user=request.user)
        form = ReportForm(request.POST or None)

        if form.is_valid():
            report = form.save(commit=False)
            report.user = user
            report.manpower = manpower
            report.save()
            return HttpResponseRedirect(manpower.get_absolute_url())

        context = {
            "manpower": manpower,
            "user": user,
            "form": form,
            "title": "Report a Manpower"
        }

        return render(request, "manpower/report.html", context)


class ReportDetailView(View):
    def get(self, request, id=None):
        report = get_object_or_404(Report, id=id)

        context = {
            "report": report,
            "title": "Report Detail"
        }

        return render(request, "manpower/report_detail.html", context)


class ReportListView(View):
    def get(self, request):
        object_list = Report.objects.all()  # .order_by("-timestamp")

        paginator = Paginator(object_list, 1)  # Show 25 contacts per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            object = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            object = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of
            # results.
            object = paginator.page(paginator.num_pages)

        context = {
            "object_list": object,
            "page_request_var": page_request_var,
            "title": "List of Reports"
        }

        return render(request, "manpower/report_list.html", context)


class ReportDeleteView(View):

    def get(self, request, id):
        instance = get_object_or_404(Report, id=id)
        instance.delete()
        return redirect('home')


class ReportVerifyView(View):

    def get(self, request, id):
        instance = get_object_or_404(Report, id=id)
        instance.verification_status = 1
        instance.save()
        return redirect('home')

website/templates/manpower/create.html
{% extends "layout/base.html" %}

{% block title %}
	Manpower | Add
{% endblock  %}


{% block content %}
    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-plus font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">Add a Manpower</span>
            </div>
        </div>
        <div class="portlet-body form">
            <form role="form" method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-body">
                	<div class="form-group">
                        <label id="name" for="{{form.name.id_for_label}}" >Name</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-user"></i>
                            </span>
                            {{form.name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="address" for="{{form.address.id_for_label}}" >Address</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-map-marker"></i>
                            </span>
                            {{form.address}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="contact_no" for="{{form.contact_no.id_for_label}}" >Contact No</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-phone"></i>
                            </span>
                            {{form.contact_no}}
                        </div>
                    </div>
                    <div class="form-group">
    					<label id="website" for="{{form.website.id_for_label}}" >Website</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-globe"></i>
                            </span>
                            {{form.website}}
                        </div>
                    </div>
                    <div class="form-group">
    					<label id="email" for="{{form.email.id_for_label}}" >Email</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-envelope"></i>
                            </span>
                            {{form.email}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="registration_no" for="{{form.registration_no.id_for_label}}" >Registration No</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-calculator"></i>
                            </span>
    						{{form.registration_no}}
                        </div>
                    </div>
                    <div class="form-group">
                    	<label id="country_list" for="{{form.country_list.id_for_label}}" >Country List</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                            <i class="fa fa-file"></i>
                            </span>
    						{{form.country_list}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label id="image" for="{{form.image.id_for_label}}" >Image</label>
                        <div class="input-group">
    						{{form.image}}
                        </div>
                    </div>
                    <button class="margin-top-20 btn blue" type="submit">Add Manpower</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

website/templates/manpower/detail.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}
	Manpower | {{manpower.name}}
{% endblock  %}


{% block content %}
	<div class="page-content">
		<div class="container">
			<div class="portlet light">
				<div class="portlet-body">
					<div class="blog-page">
						<div class="row">
							<div class="col-md-3 article-block">
							<div class="blog-tag-data">
								<img src="{{manpower.image.url}}" class="img-responsive" alt="">
							</div>
							</div>
							<div class="col-md-9 blog-sidebar">
								<div class="portlet light">
									<div class="portlet-title">
										<div class="caption">
											<span style="font-size:40px;" class="caption-subject">{{manpower.name}}</span>
											{% if not manpower.blocked %}
												{% if manpower.verification_status %}
												<span class="label label-success">Verified</span>
												{% else %}
												<span class="label label-warning">Pending</span>
												{% endif %}
											{% else %}
												<span class="label label-danger">Blocked</span>
											{% endif %}

										</div>
										<div class="actions">
											<a href="{% url 'manpower:update_manpower' manpower.slug %}" class="btn btn-circle btn-default">
											<i class="fa fa-edit"></i> Update </a>
											<a href="{% url 'manpower:report_manpower' manpower.slug %}" class="btn btn-circle btn-default">
											<i class="fa fa-edit"></i> Report </a>
											<a href="{% url 'manpower:delete_manpower' manpower.slug %}" class="btn btn-circle btn-default">
											<i class="fa fa-trash"></i> Delete</a>
											<a href="{% url 'manpower:block_manpower' manpower.slug %}" class="btn btn-circle btn-default">
											<i class="fa fa-ban"></i> Block</a>
										</div>
									</div>
									<div class="portlet-body">	
										<h4>{{manpower.average_rating}} <small><span class="fa fa-star"></span></small></h4>
										<h4><small><span class="fa fa-map-marker"></span></small>  {{manpower.address}}</h4>
										<h4><small><span class="fa fa-globe"></span></small>  <a href="{{manpower.website}}">{{manpower.website}}</a> </h4>
										<h4><small><span class="fa fa-envelope"></span></small>  {{manpower.email}}</h4>
										<h4><small><span class="fa fa-phone"></span></small>  {{manpower.contact_no}}</h4>
									</div>
								</div>
							</div>
						<!--end col-md-3-->
						</div>
						<hr/>
						<div class="row">
							<div class="col-md-9">
							<h4 class="bold">Details</h4>
								{{manpower.country_list|safe}}
								<hr>
								<div class="media">
									<h3>Reviews</h3>
									{% for review in reviews %}
									<a href="javascript:;" class="pull-left">
										<img alt="" src="{% static 'madara.jpg' %}" class="media-object">
									</a>
									<div class="media-body">
										<h4 class="media-heading"><a href="{% url 'user:show_profile' review.user.user|slugify%}">{{review.user.user}}</a>

											<span>
												{{review.timestamp|timesince}} ago
											</span>
										</h4>
										{{review.rating}} 
										<p>
										{{review.content}}
										</p>
										<hr>
									</div>
									{% endfor %}
								</div>

								<hr>
								<div class="post-comment">
									<h3>Review</h3>	
									<form role="form" action="" method="POST">
										{% csrf_token %}
										<div class="form-group">
											<h4><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span><span class="fa fa-star-o"></span></h4>
											{{form.rating}}
											{{form.content}}
										</div>
										<button class="margin-top-20 btn blue" type="submit">Post a Review</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
 

website/templates/manpower/list.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
	Manpower | Lists
{% endblock  %}


{% block content %}
<div class="page-container">
	<div class="page-content">
		<div class="container">
			{% for object in object_list%}
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="tabbable tabbable-custom tabbable-noborder">
							<div class="tab-content">
								<div id="tab_2_2" class="tab-pane active">
									<div class="row booking-results">
										<div class="col-md-12">
											<div class="booking-result">
												<div class="booking-img">
													<img src="{{object.image.url}}" alt="">
													<ul class="list-unstyled price-location">
														<li>
															<i class="fa fa-map-marker"></i> {{object.address}}
														</li>
														<li>
															<i class="fa fa-envelope"></i> {{object.email}}
														</li>
														<li>
															<i class="fa fa-phone"></i> {{object.contact_no}}
														</li>
													</ul>
												</div>
												<div class="booking-info">
													<h2>
													<a href="{{object.get_absolute_url}}">
													{{object.name}}</a>
													</h2>
													{% if not object.blocked %}
														{% if object.verification_status %}
															<span class="label label-success">Verified</span>
														{% else %}
															<span class="label label-warning">Pending</span>
														{% endif %}
													{% else %}
														<span class="label label-danger">Blocked</span>
													{% endif %}
													<h4>{{object.average_rating}} <small><span class="fa fa-star"></span></small></h4>
												</div>
											</div>
										</div>
									</div>								
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div class="margin-top-20">
						<ul class="pagination pagination-square">
					        {% if object_list.has_previous %}
					        <li>
					            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><span aria-hidden="true">&laquo;</span></a>
					        </li>
					        {% else %}
					        	<li>
					            	<a href="#"><span aria-hidden="true">&laquo;</span></a>
					            </li>
					        {% endif %}
					        {% for i in object_list.paginator.page_range %}
					       		<li {% if i == object_list.number %}class="active"{% endif %}>
					       			<a href="?{{ page_request_var }}={{i}}">{{i}}</a>
					       		</li>
					        {% endfor %}
					        {% if object_list.has_next %}
					        <li>
					            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><span aria-hidden="true">&raquo;</span></a>
					          </li>
					        {% else %}
					        	<li>
					            	<a href="#"><span aria-hidden="true">&raquo;</span></a>
					            </li>
					        {% endif %}
						</ul>
					</div>
					
				</div>
				
					
			</div>
			
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>



	
{% endblock content %}

website/templates/manpower/report_detail.html
{% extends "layout/base.html" %}

{% block title %}
	Report | {{report.manpower.name}}
{% endblock  %}


{% block content %}
<div class="page-container">
	<div class="page-content">
		<div class="container">	
			<div class="portlet light">
				<div class="portlet-body">
					<div class="portlet light">
						<div class="portlet-title">
							<div class="caption">
								<span style="font-size:40px;" class="caption-subject">{{report.title}}</span>
								{% if report.verification_status %}
									<span class="label label-success">Verified</span>
								{% else %}
									<span class="label label-warning">Pending</span>
								{% endif %}
							</div>
							<div class="actions">
								<a href="{% url 'verify_report' report.id %}" class="btn btn-circle btn-default">
								<i class="fa fa-edit"></i> Verify </a>
								<a href="{% url 'delete_report' report.id %}" class="btn btn-circle btn-default">
								<i class="fa fa-trash"></i> Delete</a>
							</div>
						</div>
						<div class="portlet-body">	
							<h4><small><span class="fa fa-user"></span></small> <a href="{% url 'user:show_profile' report.user|slugify %}">{{report.user}}</a></h4>
							<h4><small><span class="fa fa-building"></span></small> <a href="{% url 'manpower:show_manpower' report.manpower.slug %}">{{report.manpower}}</a></h4>
							<h4><small><span class="fa fa-calendar"></span></small> {{report.timestamp}}</h4>
							<hr/>
							{{report.content}}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div> 	
{% endblock content %}

website/templates/manpower/report_list.html
{% extends "layout/base.html" %}
{% load staticfiles %} 

{% block title %}
	Report | Lists
{% endblock  %}


{% block content %}
 	<!-- BEGIN PAGE CONTAINER -->
<div class="page-container">
	<div class="page-content">
		<div class="container">
			<div class="portlet light">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-file font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">objects</span>
					</div>
				</div>
				<div class="portlet-body">
					<div class="table-scrollable">
						<table class="table table-striped table-hover">
						<thead>
						<tr>
							<th>
								S.N.
							</th>
							<th>
								Report Title
							</th>
							<th>
								Reported Manpower
							</th>
							<th>
								Reporter
							</th>
							<th>
								Status
							</th>
						</tr>
						</thead>
						<tbody>
						{% for object in object_list %}
						<tr>
							<td>
								{{forloop.counter}}
							</td>
							<td>
								<a href="{{object.get_absolute_url}}">{{object.title}}</a>
							</td>
							<td>
								<a href="{% url 'manpower:show_manpower' object.manpower.slug %}">{{object.manpower}}</a>
							</td>
							<td>
							<a href="{% url 'user:show_profile' object.user|slugify %}">{{object.user}}</a>
							</td>
							<td>
								{% if object.verification_status %}
									<span class="label label-md label-success">
									Verified
									</span>
								{% else %}
									<span class="label label-md label-warning">
									Pending
									</span>
								{% endif %}
							</td>
						</tr>
						{% endfor %}
						</tbody>
						</table>
					</div>
				</div>
			</div>

			<div class="margin-top-50">
				<ul class="pagination pagination-square">
			        {% if object_list.has_previous %}
			        	<li>
			            	<a href="?{{ page_request_var }}={{ object_list.previous_page_number }} "><span aria-hidden="true">&laquo;</span></a>
			            </li>
			        {% else %}
			        	<li>
			            	<a href="#"><span aria-hidden="true">&laquo;</span></a>
			            </li>
			        {% endif %}
			        {% for i in object_list.paginator.page_range %}
			        	<li {% if i == object_list.number %}class="active"{% endif %}>
			        		<a href="?{{ page_request_var }}={{i}}">{{i}}</a>
			        	</li>
			        {% endfor %}
			        {% if object_list.has_next %}
			        	<li>
			            	<a href="?{{ page_request_var }}={{ object_list.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
			            </li>
			         {% else %}
			        	<li>
			            	<a href="#"><span aria-hidden="true">&raquo;</span></a>
			            </li>
			        {% endif %}
				</ul>
			</div>
			
		</div>
	</div>
</div>

{% endblock content %}